import './globals.css'
import { Poppins } from 'next/font/google'


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500" , "700"],
  style: ["normal","italic"]
})
export const metadata = {
  title: 'Weather App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
